package raf.dsw.classycraft.app.error;

public enum ErrorType {
    NO_NODE_SELECTED, NAME_CANNOT_BE_EMPTY, PROJECT_EXPLORER_CANNOT_BE_DELETED, NAME_EXISTS,MUST_SELECT_PROJECT,CANNOT_ADD_TO_DIAGRAM,
    INVALID_CONNECTION
}
